outputpath: experiments

feature_stream: copy-feats scp:data/car/feats.scp ark:- |
captions_file: data/car/labels/car_zh_train.json
vocab_file: data/car/vocab_zh.pth
dataloader_args:
    batch_size: 32
    num_workers: 4

scaler: StandardScaler # Can be any of sklearn.preprocessing that supports fit_partial
scaler_args:
    with_std : True
    with_mean : True        

encodermodel: GRUEncoder
encodermodel_args:
    num_layers: 1
    dropout: 0.0
    # Enables the passing of the hidden encoder state to the decoder
    use_hidden: True
    # Can be time, mean ( for last timestep, mean reduction)
    representation: mean
    hidden_size: 512
decodermodel: GRUDecoder
decodermodel_args:
    num_layers: 1
    hidden_size: 512
model: MixerModel
model_args:
    embed_size: 256
    dropout: 0.3
    init_rl_steps: 2
load_pretrained: True
pretrained: experiments/CaptionModel/2020-04-15_21-49-04_ff3090aa7f1f11eaaf720cc47ae64a5e/saved.pth
#pretrained: experiments/MixerModel/2020-05-02_00-41-05_9f0701f28bca11eab6380cc47ae64a5e/saved.pth

improvecriterion: score

optimizer: Adam
optimizer_args:
    lr: 0.00005
epochs: 25

