outputpath: experiments/hospital

feature_stream: copy-feats scp:data/hospital/fbank_dev.scp ark:- |
caption_file: data/hospital/zh_dev.json
vocab_file: data/hospital/vocab_zh.pth
dataloader_args:
    batch_size: 32
    num_workers: 4

scaler: StandardScaler # Can be any of sklearn.preprocessing that supports fit_partial
scaler_args:
    with_std : True
    with_mean : True        

encodermodel: GRUEncoder
encodermodel_args:
    num_layers: 1
    dropout: 0.0
    # Enables the passing of the hidden encoder state to the decoder
    use_hidden: True
    # Can be time, mean ( for last timestep, mean reduction)
    representation: mean
    hidden_size: 512
decodermodel: GRUDecoder
decodermodel_args:
    num_layers: 1
    hidden_size: 512
model: ScstModel
model_args:
    embed_size: 256
    dropout: 0.3

improvecriterion: score

optimizer: Adam
optimizer_args:
    lr: 0.00005
epochs: 25

