outputpath: experiments

feature_stream: copy-feats scp:data/clotho/logmel_dev.scp ark:- |
caption_file: data/clotho/dev.json
vocab_file: data/clotho/vocab.pth
zh: False
dataloader_args:
    batch_size: 32
    num_workers: 4
train_percent: 90
augments: [timemask, freqmask]

scaler: StandardScaler # Can be any of sklearn.preprocessing that supports fit_partial
scaler_args:
    with_std : True
    with_mean : True        

encodermodel: CRNNEncoder
encodermodel_args:
    use_hidden: False
decodermodel: RNNDecoder
decodermodel_args:
    num_layers: 1
    hidden_size: 512
basemodel: CaptionModel
basemodel_args:
    embed_size: 256
    dropout: 0.3
modelwrapper: ScstWrapper

load_pretrained: True
pretrained: experiments/CaptionModel/DCASE2020_submission1/saved.pth

improvecriterion: score

optimizer: Adam
optimizer_args:
    lr: 0.00005
epochs: 100

