outputpath: experiments/

feature_file: data/clotho/logmel_dev.hdf5
caption_file: data/clotho/dev.json
vocab_file: data/clotho/vocab.pth
zh: False

dataloader_args:
    batch_size: 32
    num_workers: 4
train_percent: 90
augments: [timemask, freqmask]

scaler: StandardScaler # Can be any of sklearn.preprocessing that supports fit_partial
scaler_args:
    with_std : True
    with_mean : True        

encodermodel: CRNNEncoder
encodermodel_args:
    # Enables the passing of the hidden encoder state to the decoder
    use_hidden: False
decodermodel: RNNDecoder
decodermodel_args:
    num_layers: 1
    hidden_size: 512
model: CaptionModel
model_args:
    embed_size: 256
    dropout: 0.3
#pretrained_word_embedding: data/clotho/embeddings/word2vec_word.npy
#tune_word_embedding: False
improvecriterion: score # Can also be acc | loss | score
teacher_forcing_ratio: 1.0
teacher_forcing_on_validation: False

optimizer: Adam
optimizer_args:
    lr: 0.0005
    weight_decay: 0.0
epochs: 25

